responseses = {
"hello": "hi there",
    "good morning": "good morning to you too",
    "good afternoon": "good afternoon",
    "good evening": "good evening",
    "how are you": "im doing well thanks how about you",
    "hey": "hey hows it going",
    "hi": "hello",
    "whats up": "not much you",
    "hows it going": "pretty good and you",
    "nice to see you": "nice to see you too",
    "long time no see": "yeah its been a while",
    "good to see you": "good to see you too",
    "hows everything": "everythings great what about you",
    "whats new": "not much same old how about you",
    "how have you been": "ive been good thanks for asking",
    "howdy": "howdy how are you",
    "how do you do": "im doing well and you",
    "greetings": "greetings",
    "yo": "yo whats up",
    "hiya": "hiya how are things",
    "hey there": "hey hows your day",
    "whats going on": "not much how about you",
    "hows life": "lifes good how about yours",
    "pleased to meet you": "pleased to meet you too",
    "good day": "good day to you",
    "hows your day going": "its going well how about yours",
    "morning": "morning",
    "whats happening": "not much how about you",
    "hello there": "hi there",
    "top of the morning to you": "and the rest of the day to you",
    "hows your week": "its going well how about yours",
    "how was your day": "it was great how was yours",
    "whats your plan for today": "not much just relaxing what about you",
    "what have you been up to": "just the usual how about you",
    "how are you feeling": "i feel good how about you",
    "what brings you here": "just wanted to say hi",
    "what are you doing": "just hanging out what about you",
    "how was your weekend": "it was nice how about yours",
    "good to have you here": "its great to be here",
    "how is everything with you": "everything is good what about you",
    "how is your family": "they are doing well thanks for asking",
    "what's the good word": "not much just enjoying the day",
    "how do you do today": "im doing well how about you",
    "hows your day been": "its been good how about yours",
    "what's cooking": "not much just the usual",
    "how's the weather": "its nice outside how about where you are",
    "hows your morning going": "its going well how about yours",
    "how do you feel today": "i feel great how about you",
    "good to see you again": "good to see you too",
    "whats your vibe": "just good vibes today",
    "how is work going": "its going well how about yours",
    "what brings you joy": "spending time with friends",
    "how's everything at home": "everything is good thanks",
    "what's the latest": "not much just the usual",
    "how's your spirit": "im feeling good how about you",
    "what's your story": "just the usual everyday life",
    "how's the family": "they are well thank you",
    "how's your health": "im doing well how about you",
    "what's up with you": "not much just hanging out",
    "how are your friends": "they are good thanks for asking",
    "whats your mood": "im in a good mood how about you",
    "how is life treating you": "life is treating me well",
    "what's your plan for the week": "just taking it easy",
    "how was your day at work": "it was productive how was yours",
    "how's your study going": "its going well thanks",
    "how's your day off": "its relaxing just how i like it",
    "what's your weekend like": "its been great so far",
    "how's your day shaping up": "its shaping up nicely",
    "what's your favorite part of the day": "the evening is my favorite",
    "how's your commute": "it was smooth how about yours",
    "what's your favorite time of year": "i love spring",
    "how are you today": "im doing well thank you",
    "what's your favorite thing to do": "i love reading",
    "how's your journey been": "its been good so far",
    "how do you spend your free time": "i enjoy relaxing",
    "how's your evening going": "its going well how about yours",
    "what's your current project": "im working on a few things",
    "how's your mental health": "im feeling good thanks for asking",
    "what's your favorite hobby": "i enjoy hiking",
    "how's your relationship with friends": "its great",
    "how's your day treating you": "its treating me well",
    "how's your learning going": "im enjoying it",
    "how's your experience today": "its been a good experience",
    "what is your name": "my name is chatgpt",
    "how old are you": "im ageless",
    "what do you do": "i help people with information",
    "where are you from": "im from the internet",
    "what time is it": "its about noon",
    "do you like pizza": "yes i love pizza",
    "what is your favorite color": "i like blue",
    "can you drive": "no i dont drive",
    "what is 2 plus 2": "2 plus 2 is 4",
    "where is the nearest coffee shop": "its just around the corner",
    "do you speak spanish": "yes i can speak spanish",
    "what is your favorite movie": "i dont have a favorite but i enjoy sci-fi",
    "do you like cats or dogs": "i like both",
    "what is your favorite book": "i enjoy all types of books",
    "can you cook": "i cant cook but i can share recipes",
    "how was your day": "its been great so far",
    "do you like music": "yes i love music",
    "what do you like to eat": "i dont eat but pizza sounds great",
    "can you help me with my homework": "sure id love to help",
    "what is the capital of france": "the capital of france is paris",
    "what is the largest planet": "jupiter is the largest planet",
    "what is your job": "my job is to assist and provide information",
    "can you sing": "i cant sing but i can suggest songs",
    "what is your favorite animal": "i like dolphins they are intelligent",
    "how do you spell beautiful": "beautiful is spelled b e a u t i f u l",
    "what is the weather like": "its sunny today",
    "what is your favorite season": "i think spring is nice",
    "do you drink coffee": "i dont drink but coffee sounds nice",
    "how do i make pasta": "boil water add pasta cook for 8 to 10 minutes",
    "where is the nearest gas station": "im not sure but google maps might help",
    "what is your favorite fruit": "i think apples are a classic choice",
    "how do i fix a flat tire": "use a jack to lift the car and replace the tire",
    "what is water made of": "water is made of two hydrogen atoms and one oxygen atom",
    "how do i get a passport": "you can apply at your local government office",
    "what is the tallest mountain in the world": "mount everest is the tallest mountain",
    "do you like art": "yes i appreciate art in all forms",
    "what is your favorite tv show": "i dont watch tv but friends is popular",
    "how do i change a light bulb": "turn off the power unscrew the old bulb and replace it",
    "what is 100 divided by 5": "100 divided by 5 is 20",
    "where is the eiffel tower": "the eiffel tower is in paris france",
    "what is your favorite drink": "i dont drink but many enjoy coffee",
    "how do i get better at math": "practice regularly and dont be afraid to ask questions",
    "do you know any riddles": "what has keys but cant open locks a piano",
    "what is the largest ocean": "the pacific ocean is the largest",
    "how do i start a garden": "choose a sunny spot prepare the soil and plant seeds",
    "what is your favorite ice cream flavor": "vanilla is a classic favorite",
    "how do i make a sandwich": "grab some bread add your favorite fillings and enjoy",
    "what is the capital of japan": "the capital of japan is tokyo",
    "how do i clean my room": "start by picking up items dusting surfaces and vacuuming",
    "what is the speed of light": "the speed of light is approximately 299792 km per second",
    "how do i plant a tree": "dig a hole place the tree in and cover with soil",
    "how do i bake a cake": "mix ingredients bake at 350 degrees for 30 minutes",
    "where is the bathroom": "its usually at the back or side of buildings",
    "can you tell me the news": "i dont have live updates but you can check news sites",
    "what is your favorite sport": "i think soccer is very exciting",
    "what day is it today": "its tuesday",
    "how do i get to the train station": "follow the main road for 10 minutes",
    "do you know the alphabet": "yes a b c d and so on",
    "what is gravity": "gravity is the force that attracts objects toward the earth",
    "can you write a poem": "sure roses are red violets are blue",
    "what is your favorite holiday": "i think christmas is lovely",
    "how do i fix a computer": "try restarting it and checking for updates",
    "what is the hardest natural substance": "diamond is the hardest natural substance",
    "can you help me move": "i can give you some tips but i cant physically help",
    "what is air made of": "air is mostly nitrogen and oxygen",
    "how do i start a blog": "choose a platform create content and promote it",
    "what is the best way to learn a language": "practice daily and immerse yourself in the language",
    "how do i write a letter": "start with the date greet the person and then write your message",
    "what is your favorite place": "i think the beach is a wonderful place",
    "how do i tie a tie": "there are different ways the four in hand knot is simple",
    "how do i make a smoothie": "blend fruit yogurt and ice until smooth",
    "what is the population of the world": "the world population is over 7.8 billion people",
    "how do i organize my closet": "start by decluttering then arrange items by category",
    "what is the best way to cook rice": "boil water add rice cover and simmer until done",
    "what is your favorite song": "i dont have a favorite but i enjoy all genres",
    "how do i find a job": "update your resume network and apply to openings",
    "what is your favorite season": "i enjoy the warmth of summer",
    "how do i stay motivated": "set clear goals and track your progress",
        "how do i start exercising": "start with simple exercises and gradually increase intensity",
    "what is your favorite flower": "i think roses are beautiful",
    "how do i change my password": "go to settings and select change password",
    "what is the best way to relax": "deep breathing and meditation are great for relaxation",
    "how do i learn to cook": "start by following simple recipes and practice",
    "where can i buy groceries": "most people go to supermarkets or grocery stores",
    "how do i improve my memory": "practice memorization techniques and get enough sleep",
    "how do i manage my time": "use a planner and prioritize your tasks",
    "what is your favorite car": "i dont drive but tesla is quite popular",
    "how do i learn coding": "start with an easy language like python and practice regularly",
    "what is the capital of germany": "the capital of germany is berlin",
    "how do i make friends": "be open friendly and show interest in others",
    "what is your favorite hobby": "i enjoy helping people with information",
    "how do i fold clothes": "lay the clothes flat fold in the sides and then the bottom",
    "what is the biggest country": "russia is the largest country by area",
    "how do i use a computer": "start by learning the basic functions like opening programs and typing",
    "what is the best way to travel": "many prefer flying but road trips are also fun",
    "how do i bake cookies": "mix the ingredients form dough balls and bake at 350 degrees",
    "how do i fix my phone": "try restarting it or visiting a repair shop",
    "what is your favorite snack": "i dont eat but popcorn is a popular snack",
    "how do i draw a picture": "start with simple shapes and gradually add details",
    "what is the fastest animal": "the peregrine falcon is the fastest animal",
    "how do i clean my shoes": "use a damp cloth or a brush for tougher stains",
    "how do i learn to swim": "start in shallow water and practice floating and kicking",
    "what is your favorite dessert": "i think ice cream is a popular choice",
    "how do i learn a new skill": "set small goals and practice consistently",
    "what is the capital of italy": "the capital of italy is rome",
    "how do i stay healthy": "eat a balanced diet exercise and get enough sleep",
    "how do i organize my time": "use a schedule or a to do list to plan your day",
    "what is your favorite food": "i dont eat but many people enjoy pizza",
    "how do i get a good nights sleep": "establish a bedtime routine and avoid screens before bed",
    "how do i clean my house": "start with one room at a time and clean from top to bottom",
    "what is the best way to study": "review your notes regularly and take short breaks",
    "how do i make money": "find a job or start a business",
    "what is your favorite quote": "i think be the change you wish to see in the world is inspiring",
    "how do i plan a vacation": "choose a destination set a budget and make reservations",
    "how do i improve my handwriting": "practice writing slowly and focus on forming each letter",
    "what is your favorite game": "i think chess is a great game for the mind",
    "how do i solve a problem": "break it down into smaller steps and tackle one at a time",
    "how do i stay organized": "use a planner and keep things in designated places",
    "what is your favorite city": "i think new york city is exciting",
    "how do i create a budget": "list your income and expenses and allocate money for each",
    "how do i improve my public speaking": "practice speaking in front of small groups and get feedback",
    "what is the best way to exercise": "a combination of cardio and strength training is great",
    "how do i make tea": "boil water add tea leaves or a tea bag and let it steep",
    "how do i learn to play guitar": "start with simple chords and practice regularly",
    "how do i meditate": "find a quiet place sit comfortably and focus on your breathing",
    "what is the tallest building": "the burj khalifa in dubai is the tallest building",
    "how do i clean my car": "wash the exterior and vacuum the interior",
    "what is your favorite drink": "i dont drink but many people enjoy coffee",
    "how do i quit a bad habit": "replace the habit with a positive behavior and be patient",
    "how do i improve my communication skills": "listen actively and practice expressing your thoughts clearly",
    "what is your favorite fruit": "i think strawberries are a popular choice",
    "how do i start a conversation": "ask a simple question or make a comment about your surroundings",
    "what is your favorite sport to watch": "soccer is very popular worldwide",
    "how do i manage stress": "try deep breathing exercises or take a walk",
    "how do i improve my posture": "stand up straight and engage your core muscles",
    "what is your favorite kind of music": "i enjoy all kinds of music",
    "how do i save money": "cut unnecessary expenses and set savings goals",
    "what is the best way to wake up early": "go to bed earlier and set a consistent wake up time",
    "how do i be more confident": "focus on your strengths and practice self affirmation",
    "what is your favorite thing to do on weekends": "i enjoy helping people",
    "how do i improve my vocabulary": "read regularly and learn new words",
    "what is your favorite ice cream flavor": "vanilla is a classic choice",
    "how do i take care of my skin": "cleanse moisturize and protect your skin from the sun",
    "what is your favorite animal": "i think dolphins are intelligent and friendly",
    "how do i make new friends": "be open to meeting new people and join social activities",
    "what is your favorite holiday destination": "i think tropical beaches are very relaxing",
    "how do i boost my energy": "eat healthy get enough sleep and stay hydrated",
    "how do i reduce anxiety": "practice mindfulness and take things one step at a time",
    "what is your favorite holiday": "many people enjoy christmas",
    "how do i balance work and life": "set boundaries and make time for relaxation",
    "how do i build confidence": "focus on small achievements and keep challenging yourself",
    "what is your favorite vegetable": "i think broccoli is both healthy and delicious",
    "how do i improve my listening skills": "pay attention to the speaker and avoid interrupting",
    "what is your favorite subject": "i enjoy learning about science and technology",
    "how do i learn to drive": "start with a learner's permit and practice with a licensed driver",
    "how do i improve my mood": "exercise listen to music or talk to a friend",
    "what is the best way to relax after work": "a warm bath or reading a book can help you unwind",
    "how do i start a business": "create a business plan and secure funding",
    "what is your favorite thing to do outside": "many people enjoy going for walks",
    "how do i be more productive": "set clear goals and eliminate distractions",
    "what is your favorite time of day": "many people enjoy the evening when they can relax",
    "how do i manage my emotions": "practice mindfulness and express your feelings constructively",
    "what is your favorite tree": "the oak tree is a symbol of strength",
    "how do i make a budget": "track your spending and set limits for each category",
    "what is your favorite food to cook": "i think many people enjoy making pasta",
    "how do i learn to code": "start with a beginner language like python and practice regularly",
    "what is your favorite snack": "i think many people enjoy chips or fruit",
    "how do i improve my leadership skills": "learn to listen to others and delegate tasks effectively",
    "how do i make decisions": "weigh the pros and cons and trust your instincts",
    "what is your favorite exercise": "many people enjoy jogging or yoga",
    "how do i stay focused": "take short breaks and minimize distractions",
    "what is your favorite mode of transportation": "many people prefer traveling by train or plane",
    "how do i improve my self discipline": "set small achievable goals and reward yourself for progress",
    "what is your favorite way to spend time with friends": "i think many people enjoy going out for dinner or watching movies",
    "how do i overcome fear": "face your fear gradually and build up your confidence",
    "what is your favorite season of the year": "many people enjoy summer because of the warm weather",
    "how do i stay positive": "focus on the good things in life and practice gratitude",
    "what is your favorite type of weather": "many people enjoy sunny days",
    "how do i deal with change": "embrace it as an opportunity for growth",
    "what is your favorite hobby to do indoors": "many people enjoy reading or playing video games",
    "how do i handle criticism": "listen carefully and learn from it while not taking it personally",
    "what is your favorite childhood memory": "many people cherish family vacations or playing with friends",
    "how do i achieve my goals": "set specific measurable steps and stay committed",
    "what is your favorite way to exercise": "many people enjoy cycling or swimming",
        "how do i prepare for an interview": "research the company and practice common interview questions",
    "what is your favorite drink on a hot day": "many people enjoy iced tea or lemonade",
    "how do i improve my focus while studying": "eliminate distractions and take regular breaks",
    "what is your favorite type of movie": "many people enjoy action movies or comedies",
    "how do i make a salad": "combine lettuce vegetables and dressing in a bowl",
    "what is your favorite place to visit": "many people enjoy visiting the beach or mountains",
    "how do i get over a breakup": "give yourself time to heal and focus on self care",
    "how do i stay fit": "exercise regularly and maintain a healthy diet",
    "what is your favorite type of dessert": "many people love chocolate cake",
    "how do i manage my time effectively": "prioritize your tasks and avoid procrastination",
    "how do i deal with stress at work": "take short breaks and focus on solutions not problems",
    "what is your favorite way to relax on weekends": "many people enjoy watching movies or reading",
    "how do i set goals": "make them specific measurable and time bound",
    "how do i stay motivated at work": "set personal goals and celebrate small achievements",
    "what is your favorite way to stay active": "many people enjoy running or doing yoga",
    "how do i deal with failure": "learn from your mistakes and keep moving forward",
    "what is your favorite thing to do at night": "many people enjoy stargazing or reading",
    "how do i improve my social skills": "practice talking to new people and listening actively",
    "how do i save for a big purchase": "create a savings plan and set aside money each month",
    "what is your favorite type of music to relax to": "many people enjoy classical or jazz music",
    "how do i stay hydrated": "drink water regularly and avoid sugary drinks",
    "how do i improve my problem solving skills": "break problems into smaller parts and think creatively",
    "what is your favorite way to start the day": "many people enjoy a healthy breakfast and some exercise",
    "how do i overcome procrastination": "start with small tasks and build momentum",
    "how do i improve my mental health": "practice mindfulness and make time for self care",
    "what is your favorite time of year": "many people enjoy the fall season",
    "how do i build good habits": "start small and be consistent",
    "how do i plan my day": "make a to do list and prioritize your most important tasks",
    "what is your favorite part of the day": "many people enjoy the quiet mornings",
    "how do i deal with negative thoughts": "challenge them and replace them with positive ones",
    "what is your favorite thing to do with family": "many people enjoy having dinner together or playing games",
    "how do i learn a new language": "practice daily and immerse yourself in the language",
    "how do i stay productive": "set goals take breaks and minimize distractions",
    "how do i deal with difficult people": "stay calm listen and try to understand their perspective",
    "what is your favorite type of exercise": "many people enjoy weight lifting or pilates",
    "how do i improve my writing skills": "read regularly and practice writing every day",
    "how do i prepare for a big event": "plan ahead stay organized and practice if necessary",
    "what is your favorite holiday tradition": "many people enjoy decorating the house or baking cookies",
    "how do i reduce screen time": "set limits for yourself and find other activities to enjoy",
    "how do i build strong relationships": "communicate openly and spend quality time together",
    "what is your favorite type of weather to go outside": "many people enjoy sunny but cool days",
    "how do i become more creative": "try new things and allow yourself to think outside the box",
    "what is your favorite way to unwind after a long day": "many people enjoy taking a bath or watching tv",
    "how do i deal with homesickness": "stay connected with loved ones and create a new routine",
    "how do i handle rejection": "dont take it personally and learn from the experience",
    "what is your favorite thing to do in the morning": "many people enjoy a cup of coffee and some quiet time",
    "how do i improve my cooking skills": "practice regularly and try new recipes",
    "what is your favorite way to spend a rainy day": "many people enjoy reading a book or watching a movie",
    "how do i overcome fear of public speaking": "practice in front of small groups and gradually increase your audience",
    "how do i find balance in life": "prioritize your well being and make time for what matters most",
    "what is your favorite thing to do in nature": "many people enjoy hiking or having a picnic",
    "how do i stop worrying so much": "focus on what you can control and let go of what you cant",
    "what is your favorite childhood activity": "many people enjoyed playing outside with friends",
    "how do i make time for hobbies": "schedule time for them just like any other important activity",
    "how do i keep my home clean": "create a cleaning routine and stick to it",
    "how do i make healthy eating a habit": "plan your meals and keep healthy snacks on hand",
    "what is your favorite way to exercise indoors": "many people enjoy doing workout videos or using a treadmill",
    "how do i improve my relationships with family": "communicate openly and spend time together",
    "how do i stay positive during tough times": "focus on what you are grateful for and keep moving forward",
    "what is your favorite way to spend time outdoors": "many people enjoy going for a walk or bike ride",
    "how do i organize my workspace": "keep only what you need on your desk and organize everything else",
    "how do i make friends as an adult": "join clubs or groups with similar interests and be open to meeting new people",
    "how do i start a side business": "find something youre passionate about and start small",
    "what is your favorite way to spend a sunday": "many people enjoy relaxing and preparing for the week ahead",
    "how do i balance my career and personal life": "set boundaries and make time for both",
    "what is your favorite way to spend a holiday": "many people enjoy spending time with family and friends",
    "how do i improve my concentration": "practice focusing for short periods of time and gradually increase it",
    "how do i stay motivated to exercise": "find a workout you enjoy and set small goals",
    "how do i manage my money": "create a budget and stick to it",
    "what is your favorite way to learn new things": "many people enjoy reading books or taking online courses",
    "how do i build self confidence": "focus on your strengths and practice self affirmations",
    "what is your favorite way to enjoy a sunny day": "many people enjoy going to the park or having a picnic",
    "how do i find time for self care": "schedule it into your day like any other important task",
    "how do i reduce distractions while working": "turn off notifications and create a quiet workspace",
    "what is your favorite way to celebrate a birthday": "many people enjoy having a party or spending time with loved ones",
    "how do i improve my diet": "eat more fruits vegetables and whole grains",
    "how do i deal with difficult emotions": "acknowledge them and find healthy ways to express them",
    "how do i make better decisions": "weigh the pros and cons and trust your instincts",
    "how do i find my passion": "try new things and see what excites you",
    "what is your favorite way to spend time with friends": "many people enjoy going out for a meal or watching a movie together",
    "how do i stay consistent with my goals": "set realistic goals and track your progress",
    "how do i build a healthy morning routine": "start with small habits like drinking water or stretching",
    "what is your favorite way to relax after work": "many people enjoy reading a book or watching their favorite show",
    "how do i stop overthinking": "focus on the present moment and let go of what you cant control",
    "how do i deal with loneliness": "reach out to friends or family and find social activities to join",
    "how do i improve my self esteem": "focus on your achievements and practice self love",
    "how do i stay active during the day": "take short breaks to stretch or go for a walk",
    "how do i set boundaries with others": "be clear about your limits and communicate them respectfully",
    "how do i handle peer pressure": "stay true to yourself and dont be afraid to say no",
    "what is your favorite way to spend a saturday": "many people enjoy going on an adventure or relaxing at home",
    "how do i improve my work life balance": "set boundaries and prioritize self care",
    "how do i stay calm under pressure": "take deep breaths and focus on one task at a time",
    "how do i maintain a positive attitude": "practice gratitude and focus on the good things in life",
    "how do i stop comparing myself to others": "focus on your own journey and celebrate your progress",
    "how do i improve my communication at work": "listen actively and express your thoughts clearly",
    "how do i avoid burnout": "take breaks and make time for relaxation",
    "how do i plan for retirement": "start saving early and create a financial plan",
    "what is your favorite way to spend a holiday weekend": "many people enjoy traveling or spending time with loved ones",
    "how do i improve my memory": "practice memorization techniques and get enough rest",
    "how do i deal with criticism at work": "accept constructive feedback and use it to improve",
    "how do i overcome self doubt": "focus on your strengths and accomplishments",
    "how do i handle disappointment": "accept it and find ways to move forward",
    "how do i make the most of my time": "prioritize important tasks and avoid time wasters",
    "how do i stay organized at work": "use a planner or to do list to track your tasks",
    "how do i improve my decision making skills": "analyze the situation and consider all possible outcomes",
    "how do i manage my energy levels": "get enough rest eat well and take regular breaks",
    "how do i develop a growth mindset": "embrace challenges and learn from failures",
    "how do i deal with uncertainty": "focus on what you can control and be adaptable",
    "how do i stay connected with friends": "schedule regular calls or meet ups",
    "how do i improve my leadership skills": "learn to listen and empower others",
    "how do i find a mentor": "reach out to someone you admire and ask for guidance",
    "how do i handle work related stress": "take breaks and focus on problem solving rather than dwelling",
    "how do i improve my creativity": "try new things and embrace curiosity",
    "how do i stay consistent with my workout routine": "set specific goals and track your progress",
    "how do i deal with fear of failure": "reframe it as a learning experience and keep trying",
    "how do i create a balanced lifestyle": "make time for work rest and hobbies",
    "how do i set boundaries with work": "define your work hours and stick to them",
    "how do i manage my finances better": "create a budget and stick to it",
    "how do i reduce my environmental impact": "recycle conserve energy and use less plastic",
    "how do i handle difficult conversations": "stay calm listen and be respectful",
    "how do i boost my self confidence": "focus on your strengths and celebrate small wins",
    "how do i improve my relationship with my partner": "communicate openly and spend quality time together",
    "how do i build resilience": "embrace challenges and learn from setbacks",
    "how do i deal with change in my life": "stay flexible and focus on the positives",
    "how do i find motivation to achieve my goals": "connect your goals to a bigger purpose and reward yourself",
    "how do i handle workplace conflicts": "address issues calmly and seek solutions rather than blame",
    "how do i keep learning new things": "be curious and seek out new experiences",
    "how do i handle social anxiety": "practice exposure to social situations and take small steps",
    "how do i make my work more meaningful": "align it with your personal values and goals",
    "how do i create a healthy work environment": "promote open communication and mutual respect",
    "how do i build better habits": "start with small steps and stay consistent",
    "how do i reduce clutter at home": "declutter one room at a time and donate items you dont need",
    "how do i improve my personal development": "set goals and invest time in learning new skills",
    "how do i manage my time effectively at work": "prioritize tasks and minimize distractions"
}   